### login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "john.wick@gmail.com",
  "password": "1234"
}

### signup
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
  "firstName": "keanu",
  "lastName": "reeves",
  "email": "keanu.reeves@gmail.com",
  "password": "1234",
  "bio": "this is keanu",
  "location": [-91.96432356835405, 41.00990735159587]
}

### get user by id
GET http://localhost:3000/api/users/6414ce6eaf585aaa0f48c736

### update user by id
PUT http://localhost:3000/api/users/6414ce6eaf585aaa0f48c736
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE0Y2U2ZWFmNTg1YWFhMGY0OGM3MzYiLCJmaXJzdE5hbWUiOiJqb2huIiwibGFzdE5hbWUiOiJ3aWNrIiwiZW1haWwiOiJqb2huLndpY2tAZ21haWwuY29tIiwicGFzc3dvcmQiOm51bGwsImJpbyI6InRoaXMgaXMgam9obiIsImxvY2F0aW9uIjpbLTkxLjk2NDMyMzU2ODM1NDA1LDQxLjAwOTkwNzM1MTU5NTg3XSwiX192IjowLCJwaG90byI6eyJmaWxlbmFtZSI6IjE2NzkxOTUwMzY0NTEuanBnIiwiX2lkIjoiNjQxNjdiOWM0MTkzMGZjNTk1YjM3M2M1In0sImlhdCI6MTY3OTI1NTAxOX0.QN9akSyKDEKeqkwukrcHh4LJZqydWfxsE1XpTnHTdn0
Content-Type: application/json

{
  "bio": "this is john wick!!"
}