###
POST http://localhost:3000/api/users/6414ce6eaf585aaa0f48c736/photos
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE0Y2U2ZWFmNTg1YWFhMGY0OGM3MzYiLCJmaXJzdE5hbWUiOiJqb2huIiwibGFzdE5hbWUiOiJ3aWNrIiwiZW1haWwiOiJqb2huLndpY2tAZ21haWwuY29tIiwicGFzc3dvcmQiOm51bGwsImJpbyI6InRoaXMgaXMgam9obiIsImxvY2F0aW9uIjpbLTkxLjk2NDMyMzU2ODM1NDA1LDQxLjAwOTkwNzM1MTU5NTg3XSwiX192IjowLCJpYXQiOjE2NzkxOTIyOTV9.h2zoFCsJWb8ZQGvhyUBfhc4Yt4UIn1lXKHhiT3W7Wds
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="profile.jpg"
Content-Type: image/jpeg

< ./pictures/profile.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
GET http://localhost:3000/api/users/6414ce6eaf585aaa0f48c736/photos

