### add new event
POST http://localhost:3000/api/events
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE0Y2U2ZWFmNTg1YWFhMGY0OGM3MzYiLCJmaXJzdE5hbWUiOiJqb2huIiwibGFzdE5hbWUiOiJ3aWNrIiwiZW1haWwiOiJqb2huLndpY2tAZ21haWwuY29tIiwicGFzc3dvcmQiOm51bGwsImJpbyI6InRoaXMgaXMgam9obiIsImxvY2F0aW9uIjpbLTkxLjk2NDMyMzU2ODM1NDA1LDQxLjAwOTkwNzM1MTU5NTg3XSwiX192IjowLCJpYXQiOjE2NzkwODgzOTh9.b6nMnqy7xaDhIDlYxRGGhRzbAqa9-n2GyNub2WMx0eM

{
  "title": "Event E",
  "description": "an amazing event",
  "startAt": {{$timestamp}},
  "endAt": {{$timestamp}},
  "location": [-91.96503407920258, 41.01295385898321],
  "seatLimit": 20
}

### update an event
PUT http://localhost:3000/api/events/6414e8da681a8d7a4e7ec925
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE0Y2U2ZWFmNTg1YWFhMGY0OGM3MzYiLCJmaXJzdE5hbWUiOiJqb2huIiwibGFzdE5hbWUiOiJ3aWNrIiwiZW1haWwiOiJqb2huLndpY2tAZ21haWwuY29tIiwicGFzc3dvcmQiOm51bGwsImJpbyI6InRoaXMgaXMgam9obiIsImxvY2F0aW9uIjpbLTkxLjk2NDMyMzU2ODM1NDA1LDQxLjAwOTkwNzM1MTU5NTg3XSwiX192IjowLCJpYXQiOjE2NzkwODgzOTh9.b6nMnqy7xaDhIDlYxRGGhRzbAqa9-n2GyNub2WMx0eM

{
  "title": "Event DD"
}

### delete an event
DELETE http://localhost:3000/api/events/6414e8df681a8d7a4e7ec928
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE0Y2U2ZWFmNTg1YWFhMGY0OGM3MzYiLCJmaXJzdE5hbWUiOiJqb2huIiwibGFzdE5hbWUiOiJ3aWNrIiwiZW1haWwiOiJqb2huLndpY2tAZ21haWwuY29tIiwicGFzc3dvcmQiOm51bGwsImJpbyI6InRoaXMgaXMgam9obiIsImxvY2F0aW9uIjpbLTkxLjk2NDMyMzU2ODM1NDA1LDQxLjAwOTkwNzM1MTU5NTg3XSwiX192IjowLCJpYXQiOjE2NzkwODgzOTh9.b6nMnqy7xaDhIDlYxRGGhRzbAqa9-n2GyNub2WMx0eM

### register an event
POST http://localhost:3000/api/events/6414e82c190ed4cf157188e1/registration?action=register
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE0ZDQ4OTFkYzUzYzhiYTUzZTczNDIiLCJmaXJzdE5hbWUiOiJtaWNoZWxsZSIsImxhc3ROYW1lIjoicm9kcmlndWV6IiwiZW1haWwiOiJtaWNoZWxsZS5yb2RyaWd1ZXpAZ21haWwuY29tIiwicGFzc3dvcmQiOm51bGwsImJpbyI6InRoaXMgaXMgbWljaGVsbGUiLCJsb2NhdGlvbiI6Wy05MS45NjQzMjM1NjgzNTQwNSw0MS4wMDk5MDczNTE1OTU4N10sIl9fdiI6MCwiaWF0IjoxNjc5MTY2MDIxfQ.NX6DOr-5VmFDP2gL0HCYPfibu78SgrYQGjGnP3DK41U

### unregister an event
POST http://localhost:3000/api/events/6414e82c190ed4cf157188e1/registration?action=unregister
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE0ZDRkNDFkYzUzYzhiYTUzZTczNDgiLCJmaXJzdE5hbWUiOiJrZWFudSIsImxhc3ROYW1lIjoicmVldmVzIiwiZW1haWwiOiJrZWFudS5yZWV2ZXNAZ21haWwuY29tIiwicGFzc3dvcmQiOm51bGwsImJpbyI6InRoaXMgaXMga2VhbnUiLCJsb2NhdGlvbiI6Wy05MS45NjQzMjM1NjgzNTQwNSw0MS4wMDk5MDczNTE1OTU4N10sIl9fdiI6MCwiaWF0IjoxNjc5MTY1OTA5fQ.Fyaa55iJXcmN8s8tWw7wWZjh1vntTNGDqfz2u9Pt9dk
